# Generated by Django 3.2.7 on 2021-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='mobile',
            field=models.CharField(max_length=13, verbose_name='手机'),
        ),
    ]
